# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '\u0423\u0441\u043b\u0443\u0433\u0430'},
        ),
        migrations.AlterModelOptions(
            name='sub_service',
            options={'verbose_name': '\u041f\u043e\u0434-\u0443\u0441\u043b\u0443\u0433\u0430'},
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
        migrations.AlterModelTable(
            name='sub_service',
            table='sub_service',
        ),
    ]
