# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160421_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_service',
            name='service',
        ),
        migrations.DeleteModel(
            name='Sub_service',
        ),
    ]
